/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:079c3a1e-fc24-445e-9965-634ae8ef6c3a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_OAMPtAmxQ",
    "aws_user_pools_web_client_id": "5617i4k2rmd3qo79bibtemtr1n",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://v4x5nvk56fda3fivglf4hcraem.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "iiw2e062ffd9153467b8e4e6efa97005a78210952-main",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
